version: 0.0
environment_variables:
    plaintext:
        "INPUT_FILE": ""
        "S3_WEBSITE_BUCKET": ""
        "S3_ARTIFACT_BUCKET": ""
containers:
    LambdaFunctions:
        phases:
            during_build:
                commands:
                    - zip -j lambda.zip lambda/*
                    - aws s3 cp lambda.zip "s3://${S3_ARTIFACT_BUCKET}"
                    - aws s3 sync website/ "s3://${S3_WEBSITE_BUCKET}"
        artifacts:
            files:
                - build.json
                - buildconfig.json
